In [3]:
from utils import util

In [6]:
import os
 # Iterate over all environment variables
for key, value in os.environ.items():
    print(f"{key}: {value}")

CHROME_DESKTOP: code-url-handler.desktop
COLORTERM: truecolor
CONDA_DEFAULT_ENV: yolov8
CONDA_EXE: /home/sajid/anaconda3/bin/conda
CONDA_PREFIX: /home/sajid/anaconda3/envs/yolov8
CONDA_PROMPT_MODIFIER: (yolov8) 
CONDA_PYTHON_EXE: /home/sajid/anaconda3/bin/python
CONDA_SHLVL: 2
DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1001/bus
DESKTOP_SESSION: ubuntu
DISPLAY: :1
ELECTRON_NO_ATTACH_CONSOLE: 1
GDK_BACKEND: x11
GDMSESSION: ubuntu
GIO_LAUNCHED_DESKTOP_FILE_PID: 543334
GNOME_DESKTOP_SESSION_ID: this-is-deprecated
GNOME_SHELL_SESSION_MODE: ubuntu
GPG_AGENT_INFO: /run/user/1001/gnupg/S.gpg-agent:0:1
GSETTINGS_SCHEMA_DIR: /home/sajid/anaconda3/share/glib-2.0/schemas
GTK_IM_MODULE: ibus
GTK_MODULES: gail:atk-bridge
HOME: /home/sajid
IBUS_DISABLE_SNOOPER: 1
IM_CONFIG_PHASE: 1
INVOCATION_ID: 06e4cfa91f8147b39a25120c0166aeb7
JOURNAL_STREAM: 8:47597
LANG: en_US.UTF-8
LANGUAGE: en_US:
LC_ADDRESS: ko_KR.UTF-8
LC_IDENTIFICATION: ko_KR.UTF-8
LC_MEASUREMENT: ko_KR.UTF-8
LC_MONETARY: ko_KR.UTF-8
LC_N

In [8]:
import yaml 
with open('utils/args.yaml', errors='ignore') as f:
    params = yaml.safe_load(f)

In [18]:
import os
ROOT = "/home/sajid/cctv/YOLOv8-crackV7/Dataset/"
folders = os.listdir(ROOT) 
images_folder = os.path.join(ROOT, folders[0]) 
lables_folder = os.path.join(ROOT, folders[1]) 

In [19]:
label_data = "/home/sajid/cctv/YOLOv8-crackV7/0810정석진/"
part1 = os.path.join(label_data, os.listdir(label_data)[0])
part2 = os.path.join(label_data, os.listdir(label_data)[1]) 

In [ ]:
for cam in os.listdir(part1):
    os.path.join(part1, cam)

In [6]:
import os
label_data = "/home/sajid/cctv/YOLOv8-crackV7/dataset_crack_SUNho/"
sorted(os.listdir(label_data))[5]

'checkerboard'

In [9]:
dir1 = os.path.join(label_data, sorted(os.listdir(label_data))[4])
dir1

'/home/sajid/cctv/YOLOv8-crackV7/dataset_crack_SUNho/black'

In [11]:
import os
import shutil

# Define the source and destination directories
label_data = "/home/sajid/cctv/YOLOv8-crackV7/dataset_crack_SUNho/"
dir1 = os.path.join(label_data, sorted(os.listdir(label_data))[4])
dir2 = os.path.join(label_data, sorted(os.listdir(label_data))[5])
# dir1 = "/path/to/dir1"
# dir2 = "/path/to/dir2"
image_dest = "./dataset_crack_SUNho/Dataset/images/train/"
label_dest = "./dataset_crack_SUNho/Dataset/labels/train/"
count_jpg = 0
count_json = 0
print("Started moving files from dir1")
for file in sorted(os.listdir(dir1)):
    if file.endswith(".tiff"):
        # print(f"Save .jpg with {count_jpg} filename")
        file_path = os.path.join(dir1, file)
        filename = f"N{count_jpg:04d}.jpg"
        new_file_path = os.path.join(image_dest, filename)
        shutil.copy(file_path, new_file_path)
        count_jpg += 1 
    if file.endswith(".json"):
        # print(f"Save .json with {count_json} filename")
        file_path = os.path.join(dir1, file)
        filename = f"N{count_json:04d}.json"
        new_file_path = os.path.join(label_dest, filename) 
        shutil.copy(file_path, new_file_path)
        count_json += 1
    # print(count)
    # count += 1
print("Done moving files from dir1")
print("Started moving files from dir2")
for file in sorted(os.listdir(dir2)):
    if file.endswith(".tiff"):
        filename = f"N{count_jpg:04d}.jpg"
        file_path = os.path.join(dir2, file)
        new_file_path = os.path.join(image_dest, filename)
        shutil.copy(file_path, new_file_path)
        count_jpg += 1
    if file.endswith(".json"):
        filename = f"N{count_json:04d}.json"
        file_path = os.path.join(dir2, file)
        new_file_path = os.path.join(label_dest, filename)
        shutil.copy(file_path, new_file_path) 
        count_json += 1
    # print(f"count ++++++ {count}")
    # count += 1
print("Done moving files from dir2")

Started moving files from dir1
Done moving files from dir1
Started moving files from dir2
Done moving files from dir2


In [20]:
import os
import shutil

# Define the source and destination directories
label_data = "/home/sajid/cctv/YOLOv8-crackV7/0810정석진/"
dir1 = os.path.join(label_data, os.listdir(label_data)[0])
dir2 = os.path.join(label_data, os.listdir(label_data)[1])
# dir1 = "/path/to/dir1"
# dir2 = "/path/to/dir2"
image_dest = "./Dataset/images/train/"
label_dest = "./Dataset/labels/train/"
count_jpg = 0
count_json = 0
# Iterate through each subdirectory in dir1
for subdir in sorted(os.listdir(dir1)):
    # print(subdir)
    subdir_path = os.path.join(dir1, subdir)
    if os.path.isdir(subdir_path):
        # Move all .jpg files to the image destination
        for file in sorted(os.listdir(subdir_path)):
            if file.endswith(".jpg"):
                print(f"Save .jpg with {count_jpg} filename")
                file_path = os.path.join(subdir_path, file)
                filename = f"{count_jpg:04d}.jpg"
                new_file_path = os.path.join(image_dest, filename)
                shutil.copy(file_path, new_file_path)
                count_jpg += 1 
            if file.endswith(".json"):
                print(f"Save .json with {count_json} filename")
                filename = f"{count_json:04d}.json"
                new_file_path = os.path.join(label_dest, filename)
                file_path = os.path.join(subdir_path, file)
                shutil.copy(file_path, new_file_path)
                count_json += 1
            # print(count)
            # count += 1
# Iterate through each subdirectory in dir2
for subdir in sorted(os.listdir(dir2)):
    subdir_path = os.path.join(dir2, subdir)
    if os.path.isdir(subdir_path):
        # Move all .json files to the label destination
        for file in sorted(os.listdir(subdir_path)):
            if file.endswith(".jpg"):
                filename = f"{count_jpg:04d}.jpg"
                new_file_path = os.path.join(image_dest, filename)
                file_path = os.path.join(subdir_path, file)
                shutil.copy(file_path, new_file_path)
                count_jpg += 1
            if file.endswith(".json"):
                filename = f"{count_json:04d}.json"
                new_file_path = os.path.join(label_dest, filename)
                file_path = os.path.join(subdir_path, file)
                shutil.copy(file_path, new_file_path)
                count_json += 1
            # print(f"count ++++++ {count}")
            # count += 1

Save .jpg with 0 filename
Save .json with 0 filename
Save .jpg with 1 filename
Save .json with 1 filename
Save .jpg with 2 filename
Save .json with 2 filename
Save .jpg with 3 filename
Save .json with 3 filename
Save .jpg with 4 filename
Save .json with 4 filename
Save .jpg with 5 filename
Save .json with 5 filename
Save .jpg with 6 filename
Save .json with 6 filename
Save .jpg with 7 filename
Save .json with 7 filename
Save .jpg with 8 filename
Save .json with 8 filename
Save .jpg with 9 filename
Save .json with 9 filename
Save .jpg with 10 filename
Save .json with 10 filename
Save .jpg with 11 filename
Save .json with 11 filename
Save .jpg with 12 filename
Save .json with 12 filename
Save .jpg with 13 filename
Save .json with 13 filename
Save .jpg with 14 filename
Save .json with 14 filename
Save .jpg with 15 filename
Save .json with 15 filename
Save .jpg with 16 filename
Save .json with 16 filename
Save .jpg with 17 filename
Save .json with 17 filename
Save .jpg with 18 filename
Sav

In [4]:
import os
import shutil

# Define the source and destination directories
label_data = "/home/sajid/cctv/YOLOv8-crackV7/crack_data/"
# dir1 = os.path.join(label_data, os.listdir(label_data)[0])
# dir2 = os.path.join(label_data, os.listdir(label_data)[1])
# dir1 = "/path/to/dir1"
# dir2 = "/path/to/dir2"
image_dest = "crack_data/Dataset/images/train/"
label_dest = "crack_data/Dataset/labels/train/"
count_jpg = 0
count_json = 0
# Iterate through each subdirectory in dir1
for subdir in sorted(os.listdir(label_data)):
    # print(subdir)
    subdir_path = os.path.join(label_data, subdir)
    if os.path.isdir(subdir_path):
        # Move all .jpg files to the image destination
        for file in sorted(os.listdir(subdir_path)):
            if file.endswith(".jpg"):
                print(f"Save .jpg with {count_jpg} filename")
                file_path = os.path.join(subdir_path, file)
                filename = f"{count_jpg:04d}c.jpg"
                new_file_path = os.path.join(image_dest, filename)
                shutil.copy(file_path, new_file_path)
                count_jpg += 1 
            if file.endswith(".json"):
                print(f"Save .json with {count_json} filename")
                filename = f"{count_json:04d}c.json"
                new_file_path = os.path.join(label_dest, filename)
                file_path = os.path.join(subdir_path, file)
                shutil.copy(file_path, new_file_path)
                count_json += 1

Save .jpg with 0 filename
Save .json with 0 filename
Save .jpg with 1 filename
Save .json with 1 filename
Save .jpg with 2 filename
Save .json with 2 filename
Save .jpg with 3 filename
Save .json with 3 filename
Save .jpg with 4 filename
Save .json with 4 filename
Save .jpg with 5 filename
Save .json with 5 filename
Save .jpg with 6 filename
Save .json with 6 filename
Save .jpg with 7 filename
Save .json with 7 filename
Save .jpg with 8 filename
Save .json with 8 filename
Save .jpg with 9 filename
Save .json with 9 filename
Save .jpg with 10 filename
Save .json with 10 filename
Save .jpg with 11 filename
Save .json with 11 filename
Save .jpg with 12 filename
Save .json with 12 filename
Save .jpg with 13 filename
Save .json with 13 filename
Save .jpg with 14 filename
Save .json with 14 filename
Save .jpg with 15 filename
Save .json with 15 filename
Save .jpg with 16 filename
Save .json with 16 filename
Save .jpg with 17 filename
Save .json with 17 filename
Save .jpg with 18 filename
Sav

In [1]:
import os
import json
data_dir = './Dataset/labels/train'
filenames = [x for x in sorted(os.listdir(data_dir)) if x.endswith('json')]


In [2]:
import tqdm
for filename in tqdm.tqdm(filenames):
    print(filename)
    filename = os.path.join(data_dir, filename)
    with open(filename, encoding='utf-8') as f:
        try:
            data = json.load(f)
        except Exception:
            continue
    break

  0%|          | 0/392 [00:00<?, ?it/s]

0000.json


In [7]:
shapes = data["shapes"][3]
shapes

{'label': '3',
 'points': [[1238.5964912280701, 471.30604288499023],
  [1278.3625730994152, 494.8927875243665]],
 'group_id': None,
 'description': '',
 'shape_type': 'rectangle',
 'flags': {}}

In [8]:
x1, y1 = shapes["points"][0]
x2, y2 = shapes["points"][1]

In [9]:
box_x = (x1 + x2) / 2.0 - 1
box_y = (y1 + y2) / 2.0 - 1
box_w = x2 - x1
box_h = y2 - y1
print(f"x: {box_x}\ny: {box_y}\nw: {box_w}\nh: {box_h}")

x: 1257.4795321637425
y: 482.0994152046784
w: 39.76608187134502
h: 23.586744639376263


In [13]:
import cv2
import numpy as np
image = "./Dataset/images/train/0000.jpg"
# Load the image
image = cv2.imread(image)
x1, y1 = (int(x1), int(y1))
x2, y2 = (int(x2), int(y2))
# Draw the bounding box on the image
cv2.rectangle(image, (x1, y1), (x2, y2), (0, 255, 0), 2)

# Add an arrow pointing to (x1, y1)
arrow_length = 50
arrow_angle = np.pi / 4  # Angle of the arrowhead
cv2.arrowedLine(image, (x1, y1), (x2, y2), (0, 0, 255), 2)

# # Add text within the bounding box
# text = "(x1, y1)"
# font = cv2.FONT_HERSHEY_SIMPLEX
# font_scale = 0.8
# thickness = 2
# text_size, _ = cv2.getTextSize(text, font, font_scale, thickness)
# text_x = x1 + 10  # Adjust the x-coordinate for text positioning
# text_y = y1 + text_size[1] + 10  # Adjust the y-coordinate for text positioning
# cv2.putText(image, text, (int(x1), int(y1)), font, font_scale, (0, 0, 255), thickness)

# Display the image with the bounding box
cv2.imshow('Image with Bounding Box', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
import os
import random
import shutil

# Set the paths
train_img_path = "./crack_data/Dataset/images/train"
val_img_path = "./crack_data/Dataset/images/val"

train_label_path = "./crack_data/Dataset/labels/train"
val_label_path = "./crack_data/Dataset/labels/val"

# Get the list of all image files in the source directory
image_files = [
    file
    for file in sorted(os.listdir(train_img_path))
    if file.endswith(".jpg") or file.endswith(".png")
]

# Calculate the number of images to move
percent = 0.20
num_images_to_move = int(len(image_files) * percent)

# Randomly select the images to move
images_to_move = random.sample(image_files, num_images_to_move)

print(f"{num_images_to_move} images to move.")

# Move the selected images to the validation directory
for image in images_to_move:
    image_base = image.split(".")[0]
    # move images
    shutil.move(os.path.join(train_img_path, image), os.path.join(val_img_path, image))
    print(f"Image {image} moved.")
    # move labels
    text_file = f"{image_base}.txt"
    shutil.move(
        os.path.join(train_label_path, text_file), os.path.join(val_label_path, text_file)
    )
    print(f"## Label {text_file} moved.")



122 images to move.
Image 0162c.jpg moved.
## Label 0162c.txt moved.
Image 0075c.jpg moved.
## Label 0075c.txt moved.
Image 0117c.jpg moved.
## Label 0117c.txt moved.
Image 0338c.jpg moved.
## Label 0338c.txt moved.
Image 0518c.jpg moved.
## Label 0518c.txt moved.
Image 0389c.jpg moved.
## Label 0389c.txt moved.
Image 0054c.jpg moved.
## Label 0054c.txt moved.
Image 0058c.jpg moved.
## Label 0058c.txt moved.
Image 0210c.jpg moved.
## Label 0210c.txt moved.
Image 0305c.jpg moved.
## Label 0305c.txt moved.
Image 0282c.jpg moved.
## Label 0282c.txt moved.
Image 0431c.jpg moved.
## Label 0431c.txt moved.
Image 0599c.jpg moved.
## Label 0599c.txt moved.
Image 0407c.jpg moved.
## Label 0407c.txt moved.
Image 0274c.jpg moved.
## Label 0274c.txt moved.
Image 0496c.jpg moved.
## Label 0496c.txt moved.
Image 0416c.jpg moved.
## Label 0416c.txt moved.
Image 0135c.jpg moved.
## Label 0135c.txt moved.
Image 0237c.jpg moved.
## Label 0237c.txt moved.
Image 0098c.jpg moved.
## Label 0098c.txt moved.


In [8]:
import os
import cv2
import shutil
ROOT = "/home/sajid/cctv/YOLOv8-crackV7/crack&holesamples_newSetup/"
dest_path = "/home/sajid/cctv/YOLOv8-crackV7/samples_in_jpg/"
count = 0
for folder in sorted(os.listdir(ROOT)):
    subdir_path = os.path.join(ROOT, folder)
    for file in sorted(os.listdir(subdir_path)):
        if file.endswith(".tiff"):
            file_path = os.path.join(subdir_path, file)
            # img = cv2.imread(file_path) 
            new_filename = f"{count:03d}.jpg"
            new_file_path = os.path.join(dest_path, new_filename)
            shutil.copy(file_path, new_file_path)
            # cv2.imwrite(new_file_path, img)
            count += 1
        # print(subdir_path)

In [12]:
import numpy

def resize(image, input_size):
    shape = image.shape[:2]  # current shape [height, width]
    r = min(1.0, input_size / shape[0], input_size / shape[1])
    pad = int(round(shape[1] * r)), int(round(shape[0] * r))

    w = numpy.mod(input_size - pad[0], 32) / 2
    h = numpy.mod(input_size - pad[1], 32) / 2

    if shape[::-1] != pad:  # resize
        image = cv2.resize(image, dsize=pad, interpolation=cv2.INTER_LINEAR)
    top, bottom = int(round(h - 0.1)), int(round(h + 0.1))
    left, right = int(round(w - 0.1)), int(round(w + 0.1))
    image = cv2.copyMakeBorder(image, top, bottom, left, right, cv2.BORDER_CONSTANT)

    # Convert BGR to GRAY
    image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    image = numpy.stack((image, image, image), axis=-1)
    return image

# def get_data(input_size=640):
#     ROOT = "/home/sajid/cctv/YOLOv8-crackV7/samples_in_jpg/"
#     OUT_DIR = "/home/sajid/cctv/YOLOv8-crackV7/offline_infer/"
#     dataset_loader = []
#     for file in sorted(os.listdir(ROOT)):
#         if file.endswith(".jpg"):
#             file_path = os.path.join(ROOT, file)
#             image = cv2.imread(file_path)
#             x = np.stack([resize(i, input_size) for i in image], axis=0)
#             x = x.transpose((0, 3, 1, 2))  # HWC to CHW
#             x = np.ascontiguousarray(x)  # contiguous
#             dataset_loader.append(file_path)
#     return dataset_loader
# data = get_data()

In [11]:
ROOT = "/home/sajid/cctv/YOLOv8-crackV7/samples_in_jpg/"
file_path = os.path.join(ROOT, sorted(os.listdir(ROOT))[0])
image = cv2.imread(file_path)

In [80]:
ROOT.split('/')

['', 'home', 'sajid', 'cctv', 'YOLOv8-crackV7', 'samples_in_jpg', '']

In [17]:
input_size=640
x = numpy.stack([resize(image, input_size)], axis=0) 

In [18]:
x.shape

(1, 544, 640, 3)

In [19]:
x = x.transpose((0, 3, 1, 2))
x.shape

(1, 3, 544, 640)

In [21]:
x = numpy.ascontiguousarray(x)

In [22]:
import torch
x = torch.from_numpy(x).cuda()

In [31]:
torch.min(x)

tensor(0., device='cuda:0', dtype=torch.float16)

In [26]:
x = x.half()

In [29]:
x = x / 255.

In [32]:
shape = image.shape
gain = min(x.shape[2] / shape[0], x.shape[3] / shape[1])  # gain  = old / new
pad = (x.shape[3] - shape[1] * gain) / 2, (x.shape[2] - shape[0] * gain) / 2  # wh padding


In [33]:
model = torch.load('./weights/best_v8s_newsetup.pt', 'cuda')['model'].float().fuse()

In [34]:
model.half()
model.eval()

YOLO(
  (net): DarkNet(
    (p1): Sequential(
      (0): Conv(
        (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        (relu): SiLU(inplace=True)
      )
    )
    (p2): Sequential(
      (0): Conv(
        (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        (relu): SiLU(inplace=True)
      )
      (1): CSP(
        (conv1): Conv(
          (conv): Conv2d(64, 32, kernel_size=(1, 1), stride=(1, 1))
          (relu): SiLU(inplace=True)
        )
        (conv2): Conv(
          (conv): Conv2d(64, 32, kernel_size=(1, 1), stride=(1, 1))
          (relu): SiLU(inplace=True)
        )
        (conv3): Conv(
          (conv): Conv2d(96, 64, kernel_size=(1, 1), stride=(1, 1))
          (relu): SiLU(inplace=True)
        )
        (res_m): ModuleList(
          (0): Residual(
            (res_m): Sequential(
              (0): Conv(
                (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
           

In [70]:
output = model(x)
output.shape

torch.Size([1, 6, 7140])

In [71]:
from utils import util
output = util.non_max_suppression(output, 0.1, 0.5, model.head.nc)

In [72]:
output

[tensor([[1.3275e+02, 2.7775e+02, 1.5875e+02, 2.8875e+02, 8.3984e-01, 0.0000e+00],
         [2.3225e+02, 4.6500e+02, 2.4625e+02, 4.7400e+02, 3.9893e-01, 0.0000e+00],
         [1.8425e+02, 3.0575e+02, 2.0950e+02, 3.2125e+02, 3.4961e-01, 0.0000e+00],
         [1.7825e+02, 2.9350e+02, 1.8475e+02, 2.9850e+02, 2.7051e-01, 0.0000e+00]],
        device='cuda:0')]

In [56]:
for t in output[0]:
    print(t)

tensor([132.7500, 277.7500, 158.7500, 288.7500,   0.8398,   0.0000],
       device='cuda:0')
tensor([2.3225e+02, 4.6500e+02, 2.4625e+02, 4.7400e+02, 3.9893e-01, 0.0000e+00],
       device='cuda:0')
tensor([184.2500, 305.7500, 209.5000, 321.2500,   0.3496,   0.0000],
       device='cuda:0')
tensor([1.7825e+02, 2.9350e+02, 1.8475e+02, 2.9850e+02, 2.7051e-01, 0.0000e+00],
       device='cuda:0')


In [73]:
output = output[0]

In [76]:
output[:, [0, 2]]

tensor([[132.7500, 158.7500],
        [232.2500, 246.2500],
        [184.2500, 209.5000],
        [178.2500, 184.7500]], device='cuda:0')

In [77]:
output[:, [0, 2]] -= pad[0]  
output[:, [1, 3]] -= pad[1]  
output[:, :4] /= gain
output

tensor([[5.1275e+02, 1.0542e+03, 6.1317e+02, 1.0967e+03, 8.3984e-01, 0.0000e+00],
        [8.9707e+02, 1.7775e+03, 9.5114e+02, 1.8122e+03, 3.9893e-01, 0.0000e+00],
        [7.1167e+02, 1.1624e+03, 8.0919e+02, 1.2222e+03, 3.4961e-01, 0.0000e+00],
        [6.8849e+02, 1.1150e+03, 7.1360e+02, 1.1344e+03, 2.7051e-01, 0.0000e+00]],
       device='cuda:0')

In [4]:
import torch
from torch.utils.tensorboard import SummaryWriter
from nets import nn  # Assuming your Conv class is in model.py

# Initialize your model
# model = nn.Conv(in_ch=3, out_ch=16)  # Example input/output channels
model = nn.yolo_v8_s(num_classes=2)
# Create a dummy input tensor typical of what your model expects
# For example, if your model expects a 1x3x224x224 image, you would create:
dummy_input = torch.randn(1, 3, 224, 224)

# Create a writer and log the model
writer = SummaryWriter('runs/conv_model')
writer.add_graph(model, dummy_input)
writer.close()


In [2]:
import math
height = [72, 57, 53, 48, 43]
width = 38
for h in height:
    theta = math.degrees(math.atan(h/width))
    print(theta) 

62.17590361574674
56.309932474020215
54.360190801913326
51.63251461513847
48.53229458389089


In [5]:
522 + 255 + 483

1260

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image
import numpy as np
import random
import os

# Function to parse bounding box information from the file
def parse_bboxes(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
    bboxes = [list(map(float, line.strip().split(' '))) for line in lines]
    return bboxes

# Function to convert normalized coordinates to pixel coordinates
def convert_to_pixel_coords(bbox, img_width, img_height):
    class_id, x_center, y_center, width, height = bbox
    x_center, width = x_center * img_width, width * img_width
    y_center, height = y_center * img_height, height * img_height
    x_min = int(x_center - width / 2)
    y_min = int(y_center - height / 2)
    return int(class_id), x_min, y_min, int(width), int(height)

# Function to draw bounding boxes and labels using matplotlib
def draw_bboxes(image_path, bboxes):
    # Load image
    img = Image.open(image_path).convert("RGB")
    # img_rgb = img_bgr
    img_width, img_height = img.size

    # Create figure and axes
    fig, ax = plt.subplots(1)

    # Display the image
    ax.imshow(img)

    # Convert and draw each bounding box
    for bbox in bboxes:
        class_id, x_min, y_min, width, height = convert_to_pixel_coords(bbox, img_width, img_height)
        if class_id == 0:
            rect = patches.Rectangle((x_min, y_min), width, height, linewidth=2, edgecolor='g', facecolor='none')
        else:
            rect = patches.Rectangle((x_min, y_min), width, height, linewidth=2, edgecolor='m', facecolor='none')
        ax.add_patch(rect)
        # plt.text(x_min, y_min, str(class_id), color='white', fontsize=12, backgroundcolor='red')

    plt.show()

def get_list_of_data(path, fileformat):
    """_summary_

    Args:
        path (_str_): Path of the data directory.
        fileformat (_str_): Format of the data to be retreived, e.g., "txt", "jpg", "tiff", etc. 

    Returns:
        _list_: A list contains all images path.
    """
    data_path = [os.path.join(path, f) for f in sorted(os.listdir(path)) if f.endswith(fileformat)]
    return data_path

# # Example usage
labels_path = "/hdd/KIA_Smart_Factory_Crack_Hole_detection/sajid/v5/labels/train/"
images_path = "/hdd/KIA_Smart_Factory_Crack_Hole_detection/sajid/v5/images/train/"
# List of images/labels paths
label_files = get_list_of_data(labels_path, "txt")
image_files = get_list_of_data(images_path, "png")


# Draw bounding boxes on a random subset of images
num_images_to_plot = 4 # Number of images to randomly select and plot
random_indices = random.sample(range(len(image_files)), num_images_to_plot)


random_image_label_pairs = [(image_files[i], label_files[i]) for i in random_indices]

# random_images = random.sample(image_files, num_images_to_plot)

for image, label in random_image_label_pairs:
    bboxes = parse_bboxes(label)
    draw_bboxes(image, bboxes)
